In [1]:
import numpy as np

In [3]:
print(np.__version__)

2.3.4


# Making simple arrays


In [11]:
array = np.array([[['A',"b","c"], ['D','E','F']], [['A',"b","c"], ['D','E',' ']]])
print(array.ndim)
print(array[0,0,0])

3
A


# Array Slicing

In [28]:
import numpy as np

array_1 = np.array([
    ['A', 'b', 'c', 5],
    ['D', 'E', 'F', 59],
    [2, 4, 6, 7],
    [1, 7, 1, 6]
])

# Row selection: start:end:step
print(array_1[0:4:2])

# Column selection
print(array_1[:, 3])

#both slection
print(array_1[0:2, 0:2])


[['A' 'b' 'c' '5']
 ['2' '4' '6' '7']]
['5' '59' '7' '6']
[['A' 'b']
 ['D' 'E']]


# Arithmatic


In [35]:
array_2 = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

# just normal maths
print(array_2 +1)
print(array_2 -2)
print(array_2 *10)
print(array_2 /4)
print(array_2 **5)

# vectorised math functions

print(np.sqrt(array_2))
print(np.ceil(array_2))
print(np.round(array_2))
print(np.floor(array_2))
print(np.pi *array_2 **2 )


[[ 11  21  31  41]
 [ 51  61  71  81]
 [ 91 101 111 121]
 [131 141 151 161]]
[[  8  18  28  38]
 [ 48  58  68  78]
 [ 88  98 108 118]
 [128 138 148 158]]
[[ 100  200  300  400]
 [ 500  600  700  800]
 [ 900 1000 1100 1200]
 [1300 1400 1500 1600]]
[[ 2.5  5.   7.5 10. ]
 [12.5 15.  17.5 20. ]
 [22.5 25.  27.5 30. ]
 [32.5 35.  37.5 40. ]]
[[      100000      3200000     24300000    102400000]
 [   312500000    777600000   1680700000   3276800000]
 [  5904900000  10000000000  16105100000  24883200000]
 [ 37129300000  53782400000  75937500000 104857600000]]
[[ 3.16227766  4.47213595  5.47722558  6.32455532]
 [ 7.07106781  7.74596669  8.36660027  8.94427191]
 [ 9.48683298 10.         10.48808848 10.95445115]
 [11.40175425 11.83215957 12.24744871 12.64911064]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
[[ 

# Broadcasting

In [41]:
array_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [1,2,3,4],
                    [1,2,3,4],])
array_2 = np.array([[1],[2],[3],[4]])
print(array_1.shape)
print(array_2.shape)
print(array_1*array_2)


(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [ 3  6  9 12]
 [ 4  8 12 16]]


# Aggregate functions

In [47]:
array = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [1,2,3,4],
                    [1,2,3,4],])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmax(array))
print(np.argmin(array))

56
3.5
2.0615528128088303
4.25
1
8
7
0


# Filtering

In [52]:
ages = np.array([[23,5,33,75,35,86,23,],
                 [33,32,35,38,35,34,33]])

teenagers = ages[ages < 18]
print(teenagers)
old =  ages[ages > 18]
print(old
      )

[5]
[23 33 75 35 86 23 33 32 35 38 35 34 33]


# Random Numbers

In [57]:
rng = np.random.default_rng()

print(rng.integers(low=1,high=101))

90


In [ ]:
#Floating point numbers
print(np.random.uniform(-1,10))

2.593691346482787


: 